# Generated by Django 3.2 on 2021-06-03 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='exam',
            new_name='course',
        ),
    ]
